### ISSUE TITLE
RuntimeError: generator raised StopIteration when running scripts/baselines/ham.py

### ISSUE THREAD

**Issue by Jiaxin-Pei** [Anna146/PRIDE#1]
I have followed all the data pipelines to prepare the input data, however, when running ham.py, I got the following error:

```
{'hidden_size': 200, 'lr': 0.01, 'batch_size': 32, 'hidden_size_attention': 150, 'best_epoch': '13', 'best_threshold': 0.48}
Epoch 0
Epoch [1/50], Batch [1], Loss: 0.7585
Traceback (most recent call last):
  File "/Users/pedropei/PycharmProjects/PRIDE/scripts/fast_utils.py", line 185, in feature_gen_ham
    sample.load(f_in)
  File "/Users/pedropei/PycharmProjects/PRIDE/scripts/fast_utils.py", line 35, in load
    self.__dict__ = pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedropei/PycharmProjects/PRIDE/scripts/fast_utils.py", line 187, in feature_gen_ham
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pedropei/PycharmProjects/PRIDE/scripts/baselines/ham.py", line 229, in <module>
    train()
  File "/Users/pedropei/PycharmProjects/PRIDE/scripts/baselines/ham.py", line 183, in train
    for i, features in enumerate(batch_accumulator):
  File "/Users/pedropei/PycharmProjects/PRIDE/scripts/fast_utils.py", line 199, in BatchAccumulator
    sample = next(stream)
  File "/usr/local/lib/python3.9/site-packages/pescador/mux.py", line 194, in iterate
    yield six.advance_iterator(active_mux.streams_[idx])
  File "/usr/local/lib/python3.9/site-packages/pescador/core.py", line 204, in iterate
    for n, obj in enumerate(active_streamer.stream_):
RuntimeError: generator raised StopIteration
```
Would it be possible for you to help me with this issue?
Thanks!

**Comment by Anna146** [comment]
did you check that all created files are actually not empty?

**Comment by Jiaxin-Pei** [comment]
> 
Heyy sorry for my late reply. Yes, I checked and they are not empty

**Comment by Anna146** [comment]
Hmm can you maybe debug it? you can maybe leave just one file in training directory and see if it works on one file? If the problem persists you can try to manually load the InputFeatures class?
Let me know if you could do it. Sorry for asking you that - it works for me so probably not a bug in implementation. Did you check that all requirements match - maybe it is an issue with pescador version?

**Comment by Jiaxin-Pei** [comment]
> Hmm can you maybe debug it? you can maybe leave just one file in training directory and see if it works on one file? If the problem persists you can try to manually load the InputFeatures class? Let me know if you could do it. Sorry for asking you that - it works for me so probably not a bug in implementation. Did you check that all requirements match - maybe it is an issue with pescador version?

Thanks for your reply! Sure, let me try to debug it. If it works fine for you, then it's probably some issues at my end. Thanks again.

**Comment by Younsuk11** [comment]
Did you solve this problem? Let me know the right way. I also got stuck on the same problem...
